server:
  port: 8761

spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:http://localhost:8888  # <-- This line is required in Spring Boot 3+

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
     prefer-ip-address: true
     hostname: localhost