server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_order
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  application:
    name: order-service

# this means register api-gateway to eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
     prefer-ip-address: true
     hostname: localhost