server:
  port: 9091

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
